version: '3'

tasks:
  dev:frontend:
    dir: ./frontend
    cmds:
      - npm run dev -- --port 9245 --host 127.0.0.1

  build:
    cmds:
      - go build -o build/bin/siren .

  run:
    cmds:
      - ./build/bin/siren
