// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDevice'](arg1, arg2, arg3);
}

export function CheckSystemRequirements() {
  return window['go']['main']['App']['CheckSystemRequirements']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetLocalInputs() {
  return window['go']['main']['App']['GetLocalInputs']();
}

export function GetLocalOutputs() {
  return window['go']['main']['App']['GetLocalOutputs']();
}

export function RemoveDevice(arg1) {
  return window['go']['main']['App']['RemoveDevice'](arg1);
}

export function StartTunnel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTunnel'](arg1, arg2, arg3, arg4);
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}
