// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function AddDevice(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckSystemRequirements():Promise<Record<string, boolean>>;

export function GetDevices():Promise<Array<core.Device>>;

export function GetLocalInputs():Promise<Array<core.AudioNode>>;

export function GetLocalOutputs():Promise<Array<core.AudioNode>>;

export function RemoveDevice(arg1:string):Promise<void>;

export function StartTunnel(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StopTunnel():Promise<void>;
